spring.application.name=OurMemoriesEduSmart

#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

#JWT
jwt.secret=${SECRET}
jwt.expiration=${EXPIRATION}

#AUTH
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}

# ===============================
# EMAIL CONFIG (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.from=ourmemoriesapplicationoffice@gmail.com

app.base-url=http://localhost:8080

# Stripe Configuration
stripe.secret.key=sk_test_51Qxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
stripe.webhook.secret=whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
stripe.publishable.key=pk_test_51Qxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Payment Configuration
payment.proof.upload.path=${PAYMENT_PATH}
payment.max-file-size=${MAX_SIZE}

# Frontend URL
frontend.url=${FRONTEND_URL}

# Logging
logging.level.com.ourmemories.OurMemoriesEduSmart=DEBUG
logging.level.com.stripe=DEBUG


